"""primeira migracao

Revision ID: 178acad367ac
Revises: 
Create Date: 2025-09-05 23:02:23.390250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178acad367ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('sintomas', sa.Text(), nullable=False),
    sa.Column('risco', sa.String(length=20), nullable=True),
    sa.Column('prioridade_sus', sa.Boolean(), nullable=True),
    sa.Column('gestante', sa.Boolean(), nullable=True),
    sa.Column('lactante', sa.Boolean(), nullable=True),
    sa.Column('pcd', sa.Boolean(), nullable=True),
    sa.Column('crianca_colo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
